# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/gserv.rb'

Hoe.new('gserv', Gserv::VERSION) do |p|
  # p.rubyforge_name = 'gservx' # if different than lowercase project name
  p.developer('Jordan Dobson', 'jordandobson@gmail.com')
end

# vim: syntax=Ruby
